title: Sridhar Kandi
logo: assets/sridhar-modified.png
#description: Data Science Innovator | Turning Data into Decisions
# show_downloads: true
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default
